title: Major Games
email: majorgamesstl@gmail.com
description: "Major Games - St. Louis, MO"
baseurl: ""
url: ""

show_excerpts: true

ebay_username: major_game_cole
tcgplayer_ref: a462b173
github_username:  majorgamesstl

theme: minima
plugins:
  - jekyll-feed
